name: helloworld
description: "A new Flutter project."

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  image_picker: ^0.8.7+4
  google_ml_kit: ^0.7.0
  flutter_barcode_scanner: ^2.0.0

  # firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4

  # bloc
  flutter_bloc: ^8.1.6

  equatable: ^2.0.5

  # custom path
  user_repository:
    path: packages/user_repository

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
  