// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzcthZ0tx8escpHbgSGbdsuQRjQFd07as',
    appId: '1:380421220342:web:b4b0e4ff31cfbcd32609d7',
    messagingSenderId: '380421220342',
    projectId: 'library-manage-d1420',
    authDomain: 'library-manage-d1420.firebaseapp.com',
    storageBucket: 'library-manage-d1420.appspot.com',
    measurementId: 'G-YVXKHEVGFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo5Wa4OKrTNW-eB7d926gYAo2hEgzjlnw',
    appId: '1:380421220342:android:8e21c56b22eefd8e2609d7',
    messagingSenderId: '380421220342',
    projectId: 'library-manage-d1420',
    storageBucket: 'library-manage-d1420.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkRwqqJbrdpeDaGCVqHpxA8Hi29_WinpU',
    appId: '1:380421220342:ios:93eea4a47b96af332609d7',
    messagingSenderId: '380421220342',
    projectId: 'library-manage-d1420',
    storageBucket: 'library-manage-d1420.appspot.com',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkRwqqJbrdpeDaGCVqHpxA8Hi29_WinpU',
    appId: '1:380421220342:ios:93eea4a47b96af332609d7',
    messagingSenderId: '380421220342',
    projectId: 'library-manage-d1420',
    storageBucket: 'library-manage-d1420.appspot.com',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzcthZ0tx8escpHbgSGbdsuQRjQFd07as',
    appId: '1:380421220342:web:ae36a83a764d35a62609d7',
    messagingSenderId: '380421220342',
    projectId: 'library-manage-d1420',
    authDomain: 'library-manage-d1420.firebaseapp.com',
    storageBucket: 'library-manage-d1420.appspot.com',
    measurementId: 'G-3Z90BY5EYY',
  );
}
